name: handson_k8s

dependencies:
  - python~=3.9.0
  - pip~=22.3.0
  - pip:
    - boto3~=1.18.0
    - click==8.1.3
    - dynaconf==3.1.5
    - flake8==3.9.2
    - flask~=2.0.0
    - importlib-metadata<5.0
    - ipykernel~=6.4.0
    - jupyter-client<7.0,>=5.1    
    - kedro[spark.SparkDataSet]~=0.18.0
    - kedro-viz~=5.2.0
    - mypy==0.910
    - matplotlib~=3.5.0
    - mlflow==1.30.1
    - numpy~=1.23.0
    - pandas~=1.5.3
    - protobuf~=3.20.1    
    - pylint~=2.14.0
    - pyspark==3.1.2
    - pytest-cov~=3.0
    - pytest-mock>=1.7.1, <2.0
    - pytest~=6.2
    - scikit-learn~=1.0.0
    - seaborn==0.11.2
    - shap~=0.41.0
    - textblob==0.17.1
    - typed-ast==1.4.3
    - wget==3.2
  